name: tapsell_plus
description: Tapsell Plus is a mediation SDK for in-app advertising purposes. TapsellPlus allows usage of multiple adNetworks and decides which one to to show at the moment to increase total income.
version: 2.2.3
homepage: https://github.com/tapsellorg/TapsellPlusSDK-FlutterPlugin
documentation: https://docs.tapsell.ir/plus-sdk/flutter/main/
issue_tracker: https://github.com/tapsellorg/TapsellPlusSDK-FlutterPlugin/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: ir.tapsell.plus.flutter
        pluginClass: TapsellPlusFlutterPlugin
